name: hail_detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - pytorch-lightning=1.8.1
  - matplotlib=3.6.2
  - numpy=1.23.4
  - pandas=1.5.1
  - scikit-learn=1.1.3
  - streamlit=1.15.1
  - pillow=9.3.0
  - pyyaml=6.0
  - requests=2.28.1
  - xarray=2022.11.0
  - netcdf4=1.6.1
  - pip:
    - nexradaws==1.1.0
    - psutil==5.9.4